# Dependabot configuration for automated dependency updates
# This helps keep dependencies secure by automatically creating PRs for updates

version: 2
updates:
  # Backend npm dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ludia8888"
    assignees:
      - "ludia8888"
    commit-message:
      prefix: "security"
      prefix-development: "deps"
      include: "scope"
    # Group security updates for faster processing
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
    # Ignore major version updates for these packages (manual review required)
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jsonwebtoken"
        update-types: ["version-update:semver-major"]

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:30"
    open-pull-requests-limit: 10
    reviewers:
      - "ludia8888"
    assignees:
      - "ludia8888"
    commit-message:
      prefix: "security"
      prefix-development: "deps"
      include: "scope"
    # Group similar updates together
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "vitest*" 
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"
        update-types:
          - "minor"
          - "patch"
    # Ignore major version updates for these packages (manual review required)
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]

  # Root level npm dependencies (if any)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ludia8888"
    assignees:
      - "ludia8888"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ludia8888"
    assignees:
      - "ludia8888"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"