# Main Render configuration file
# This file is used when deploying multiple services from the root directory

services:
  # Backend API Service
  - type: web
    name: pca-hijab-backend
    runtime: node
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - ShowMeTheColor/**
        - frontend/**
        - docs/**
        - "*.md"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://pca-hijab.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_API_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: AI_API_URL
        value: https://showmethecolor-api.onrender.com
      - key: CORS_ORIGIN
        value: https://pca-hijab.vercel.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d

  # AI API Service (ShowMeTheColor)
  - type: web
    name: showmethecolor-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./ShowMeTheColor/Dockerfile.render
    rootDir: .
    buildFilter:
      paths:
        - ShowMeTheColor/**
      ignoredPaths:
        - backend/**
        - frontend/**
        - docs/**
        - "*.md"
        - .github/**
    envVars:
      - key: PORT
        value: 8000

databases:
  - name: pca-hijab-db
    plan: free
    region: singapore