# Main Render configuration file
# This file is used when deploying multiple services from the root directory

services:
  # Backend API Service
  - type: web
    name: pca-hijab-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: singapore
    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - ShowMeTheColor/**
        - frontend/**
        - docs/**
        - "*.md"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: CLIENT_URL
        value: https://pca-hijab.vercel.app,https://noorai-ashy.vercel.app,https://noorai.vercel.app,https://pca-hijab-frontend.vercel.app
      - key: DATABASE_URL
        value: postgresql://pca_hijab_db_fm69_user:VnyKtJJUqgFhE95HRD6EeG6iUoCoax2O@dpg-d39furqli9vc7380a6vg-a.singapore-postgres.render.com/pca_hijab_db_fm69
      - key: ADMIN_API_KEY
        value: gYlBtxtCYYAtPD6HaHZLKmB3zTNtk9mY
      - key: JWT_SECRET
        value: 8a111WXL3dZy6/N7SyzkJgOp36Nvs9XHWAhAnViD6GY=
      - key: JWT_REFRESH_SECRET
        value: SVf8UKYy6m8Lr9dVTGUzCzIcjS0g81CaxkVcExJfDB4=
      - key: EMAIL_ENABLED
        value: true
      - key: RESEND_API_KEY
        value: re_PspAYXmP_37xPU2MiBMZFiCD2yqwEL1XK
      - key: EMAIL_FROM
        value: PCA-HIJAB <onboarding@resend.dev>

  # AI API Service (ShowMeTheColor)
  - type: web
    name: showmethecolor-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./ShowMeTheColor/Dockerfile.render
    rootDir: .
    buildFilter:
      paths:
        - ShowMeTheColor/**
      ignoredPaths:
        - backend/**
        - frontend/**
        - docs/**
        - "*.md"
        - .github/**
    envVars:
      - key: PORT
        value: 8000

# Database is already created and managed separately