services:
  - type: web
    name: pca-hijab-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://pca-hijab.vercel.app
      - key: JWT_SECRET
        generateValue: true