services:
  - type: web
    name: pca-hijab-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_API_KEY
        generateValue: true