services:
  - type: web
    name: pca-hijab-backend
    runtime: node
    plan: free
    region: singapore
    buildCommand: ./render-build.sh
    startCommand: npm start
    buildFilter:
      paths:
        - backend/**
        - package.json
        - package-lock.json
      ignoredPaths:
        - ShowMeTheColor/**
        - frontend/**
        - docs/**
        - "*.md"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://pca-hijab.vercel.app,https://noorai-ashy.vercel.app,https://noorai.vercel.app,https://pca-hijab-frontend.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_API_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: AI_API_URL
        value: https://your-ai-api-url.com
      - key: CORS_ORIGIN
        value: https://pca-hijab.vercel.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d