// Seasonal color recommendations (based on professional personal color guidelines)
export const SEASON_COLORS = {
  spring: {
    bestColors: [
      { name: 'Coral', hex: '#FF7F50', description: 'Warm and vibrant impression' },
      { name: 'Apricot', hex: '#FBCEB1', description: 'Soft and radiant atmosphere' },
      { name: 'Bright Gold', hex: '#FFD700', description: 'Bright and energetic feeling' },
      { name: 'Bright Turquoise', hex: '#48D1CC', description: 'Fresh and clear image' },
      { name: 'Peach', hex: '#FFE5B4', description: 'Soft warm glow' },
      { name: 'Light Coral', hex: '#F08080', description: 'Gentle warmth' },
      { name: 'Yellow Green', hex: '#9ACD32', description: 'Fresh spring feeling' },
      { name: 'Salmon', hex: '#FA8072', description: 'Warm and friendly' },
      { name: 'Light Orange', hex: '#FFB347', description: 'Bright and cheerful' },
      { name: 'Mint', hex: '#98FB98', description: 'Fresh and clean' },
    ],
    worstColors: [
      { name: 'Black', hex: '#000000', description: 'Looks too heavy' },
      { name: 'Cool Gray', hex: '#708090', description: 'Makes skin look dull' },
      { name: 'Cool Blue', hex: '#4682B4', description: 'Makes face look pale' },
      { name: 'Cool Pink', hex: '#DDA0DD', description: 'Looks unnatural' },
      { name: 'Burgundy', hex: '#800020', description: 'Too dark and heavy' },
      { name: 'Navy', hex: '#000080', description: 'Too cold' },
      { name: 'Charcoal', hex: '#36454F', description: 'Makes complexion dull' },
      { name: 'Deep Purple', hex: '#483D8B', description: 'Too cool toned' },
      { name: 'Slate Blue', hex: '#6A5ACD', description: 'Clashes with warm tone' },
      { name: 'Dark Brown', hex: '#654321', description: 'Too heavy' },
    ],
  },
  summer: {
    bestColors: [
      { name: 'Light Blue', hex: '#ADD8E6', description: 'Cool and refreshing impression' },
      { name: 'Lavender', hex: '#E6E6FA', description: 'Elegant and soft feeling' },
      { name: 'Rose Pink', hex: '#FFC0CB', description: 'Feminine and romantic atmosphere' },
      { name: 'Light Gray', hex: '#D3D3D3', description: 'Sophisticated and calm image' },
      { name: 'Powder Pink', hex: '#FFE4E1', description: 'Soft and delicate' },
      { name: 'Sky Blue', hex: '#87CEEB', description: 'Clear and fresh' },
      { name: 'Periwinkle', hex: '#CCCCFF', description: 'Cool and elegant' },
      { name: 'Mint Blue', hex: '#B0E0E6', description: 'Fresh summer feeling' },
      { name: 'Pale Yellow', hex: '#FFFFE0', description: 'Soft light tone' },
      { name: 'Lilac', hex: '#C8A2C8', description: 'Gentle cool tone' },
    ],
    worstColors: [
      { name: 'Black', hex: '#000000', description: 'Looks too strong' },
      { name: 'Bright Orange', hex: '#FF8C00', description: 'Makes skin look yellowish' },
      { name: 'Bright Yellow', hex: '#FFFF00', description: 'Makes face look dull' },
      { name: 'Warm Brown', hex: '#8B4513', description: 'Looks disharmonious' },
      { name: 'Rust', hex: '#B7410E', description: 'Too warm and heavy' },
      { name: 'Olive', hex: '#808000', description: 'Makes complexion muddy' },
      { name: 'Burnt Orange', hex: '#CC5500', description: 'Too intense' },
      { name: 'Gold', hex: '#FFD700', description: 'Too warm' },
      { name: 'Khaki', hex: '#C3B091', description: 'Looks dull' },
      { name: 'Terracotta', hex: '#C65D00', description: 'Clashes with cool tone' },
    ],
  },
  autumn: {
    bestColors: [
      { name: 'Olive Green', hex: '#708238', description: 'Natural and deep impression' },
      { name: 'Mustard Yellow', hex: '#FFDB58', description: 'Warm and soft feeling' },
      { name: 'Terracotta', hex: '#E2725B', description: 'Healthy and vibrant atmosphere' },
      { name: 'Chocolate Brown', hex: '#7B3F00', description: 'Luxurious and stable image' },
      { name: 'Burnt Orange', hex: '#CC5500', description: 'Rich autumn warmth' },
      { name: 'Rust', hex: '#B7410E', description: 'Deep warm tone' },
      { name: 'Camel', hex: '#C19A6B', description: 'Sophisticated neutral' },
      { name: 'Bronze', hex: '#CD7F32', description: 'Warm metallic glow' },
      { name: 'Khaki', hex: '#C3B091', description: 'Earthy and natural' },
      { name: 'Copper', hex: '#B87333', description: 'Rich warm accent' },
    ],
    worstColors: [
      { name: 'Black', hex: '#000000', description: 'Looks too heavy' },
      { name: 'Cool Blue', hex: '#4169E1', description: 'Makes skin look dull' },
      { name: 'Cool Gray', hex: '#778899', description: 'Looks lifeless' },
      { name: 'Light Pink', hex: '#FFB6C1', description: 'Looks unnatural' },
      { name: 'Icy Blue', hex: '#B0E0E6', description: 'Too cool toned' },
      { name: 'Lavender', hex: '#E6E6FA', description: 'Clashes with warm tone' },
      { name: 'Silver', hex: '#C0C0C0', description: 'Too cool' },
      { name: 'Cool Purple', hex: '#9370DB', description: 'Makes complexion dull' },
      { name: 'Mint', hex: '#98FB98', description: 'Too fresh for deep tone' },
      { name: 'Baby Blue', hex: '#89CFF0', description: 'Looks washed out' },
    ],
  },
  winter: {
    bestColors: [
      { name: 'Navy Blue', hex: '#000080', description: 'Deep and vivid impression' },
      { name: 'Deep Purple', hex: '#800080', description: 'Luxurious and mysterious feeling' },
      { name: 'Cool Red', hex: '#DC143C', description: 'Intense and sophisticated atmosphere' },
      { name: 'Cool Gray', hex: '#696969', description: 'Chic and modern image' },
      { name: 'Royal Blue', hex: '#4169E1', description: 'Bold and confident' },
      { name: 'Magenta', hex: '#FF00FF', description: 'Vibrant cool tone' },
      { name: 'Emerald', hex: '#50C878', description: 'Cool jewel tone' },
      { name: 'Black', hex: '#000000', description: 'Classic and strong' },
      { name: 'Pure White', hex: '#FFFFFF', description: 'Crisp contrast' },
      { name: 'Hot Pink', hex: '#FF69B4', description: 'Cool bright accent' },
    ],
    worstColors: [
      { name: 'Warm Brown', hex: '#964B00', description: 'Makes face look dull' },
      { name: 'Warm Orange', hex: '#FF8C00', description: 'Makes skin look yellowish' },
      { name: 'Warm Yellow', hex: '#FFD700', description: 'Looks disharmonious' },
      { name: 'Warm Green', hex: '#8FBC8F', description: 'Looks lifeless' },
      { name: 'Beige', hex: '#F5F5DC', description: 'Too muted' },
      { name: 'Camel', hex: '#C19A6B', description: 'Too warm and soft' },
      { name: 'Peach', hex: '#FFE5B4', description: 'Clashes with cool tone' },
      { name: 'Coral', hex: '#FF7F50', description: 'Too warm' },
      { name: 'Olive', hex: '#808000', description: 'Looks muddy' },
      { name: 'Rust', hex: '#B7410E', description: 'Too earthy' },
    ],
  },
} as const;

export type SeasonType = keyof typeof SEASON_COLORS;